services:
  db:
    image: postgres:14.15-alpine3.21
    environment:
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "fastapi"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
volumes:
    postgres:
